### ISSUE TITLE
分享和Tab全局设置问题

### ISSUE THREAD

**Issue by awong1900** [oodzchen/CNode-V#1]
首先感谢楼主开源出来。整个框架和功能形态都很完善了。
我是下载编译，用了我自己部署的教练社区 https://bbs.zuqiuxunlian.com 的API做的测试。

1. 社区有个很重要的推广是分享，当分享到QQ群或微信群，用内置浏览器打开后会发现无法跳转到首页访问。而且分享文章不是文章的图文，而是首页图文。
2. 代码Tab部分是否可以全局设置，方便修改。

感谢开源。

**Comment by oodzchen** [comment]
分享功能目前只能用浏览器的分享接口，我最多能做到调起系统级的分享，不过也只是分享url信息而已。至于在微信和QQ的图文设置，需要申请微信开发者账号，做专门的配置，貌似作为个人开发者还没发搞到这个账号。

Tab的全局设置我没太懂你的意思，能否详细说明一下。

**Comment by awong1900** [comment]
Tab栏是社区的分享，问答，招聘这些分栏设置。好像代码里有好几个地方需要设置。希望是有个全局设置的地方。 
分享了解是受限于框架做不了。图文像cnodejs web版本分享会默认把文章的首图放在分享显示，不需要额外的配置。 不过既然wpa不能分享某一页的话，这个也没有意义了。

**Comment by oodzchen** [comment]
Tab数据的配置入口我是单独提取出来了的，在 [src/data/tabs.json](https://github.com/oodzchen/CNode-V/blob/master/src/data/tabs.json) 这个文件里面，只要在这一个地方配置就行了，其中`category`字段值跟提交到后端的`tab`字段的值同步，`name`字段是显示到前端的文本。
至于你说的有好几个地方需要设置，我理解是代码逻辑比较分散，这块我确实没写好，不过这部分你可以暂时不管，只需改配置数据就行了。

**Comment by awong1900** [comment]
好的。谢谢， 我看到过这个位置。我再测试一下。
